### ISSUE TITLE
App crashes when setting amplitude on 10.2

### ISSUE THREAD

**Issue by jordanful** [alankarmisra/SwiftSiriWaveformView#11]
Hi, 

I'm following the setup exactly via Cocoapods, but when I run my app, it crashes on the line where I set the amplitude of the waveform, even when I hardcode the amplitude to a static value.

Podfile is: 
`pod 'SwiftSiriWaveformView'`

- I then dragged a View onto my ViewController and specified its class, via Storyboard, as `SwiftSiriWaveformView`. 
- Dragged out an IBOutlet `@IBOutlet weak var waveForm: SwiftSiriWaveformView!`
- In another IBAction, I start the AVAudioRecorder and convert the dB of it to amps 
```
 trackRec?.record()
                    let db = trackRec?.averagePower(forChannel: 0)
                    let result = pow(10.0, db! / 20.0) * 120.0
                    waveForm.amplitude = CGFloat(result) 
```

The application crashes on the last line, without much logging help. I'm pretty new to iOS development, so maybe there are more helpful logs I can provide outside of what I see in the console, which is just `(lldb)`. 

Thanks for any help in advance.

**Comment by alankarmisra** [comment]
You see nothing printed on your console before lldb? If you do, copy paste that here and I can have a look. If lldb shows you nothing, could you create a minimal project file that reproduces the error and attach it here? I'll have a look at it. You may also want to look at: 

https://www.raywenderlich.com/10209/my-app-crashed-now-what-part-1 

to get some hints on how to better debug your app.

**Comment by jordanful** [comment]
Thanks for the quick reply and the very helpful link @alankarmisra ! 

Ok, so my console was pretty noisy and I did find this line logged when the ViewController loads: 
`Unknown class SwiftSiriWaveformView in Interface Builder file.`

I'm a bit confused, though. The readme indicates I should be setting the UIView's class as `SCSiriWaveformView`, and not `SwiftSiriWaveformView`

But, `SwiftSiriWaveformView` seems to 'work' in the sense that XCode recognizes it and shows all the custom properties in Interface Builder and such. 

Should I be using `SCSiriWaveformView` instead?

**Comment by alankarmisra** [comment]
Just click on your waveform view and make sure you've selected the SwiftSiriWaveformView from the module dropdown. 
![screen shot 2016-12-22 at 7 03 10 pm](https://cloud.githubusercontent.com/assets/762834/21427238/643092d6-c879-11e6-9424-606ae6a67bcb.png)

The readme indicates that my code was inspired by SCSiriWaveformView (it doesn't suggest that's the name you should use) :) You've done the right thing by setting the class to SwiftSiriWaveformView.

**Comment by jordanful** [comment]
It was the Module that wasn't set - thanks again @alankarmisra.
