### ISSUE TITLE
CocoaPods Installation Not Getting Most Recent Update

### ISSUE THREAD

**Issue by dispatchswift** [alankarmisra/SwiftSiriWaveformView#12]
I've added `pod "SwiftSiriWaveformView"` to my Podfile as suggested, but I'm not seeing the code to programmatically create the view. I'm only seeing `init(coder: NSCoder)`?

Looks like there needs to be a new release after the merge [Support for programmatically adding the SwiftSiriWaveformView](https://github.com/alankarmisra/SwiftSiriWaveformView/commit/bb29a6c6bc1ecd79376f3566d84754f61f16d7e3) was made because there's 2 commits to master since 2.0.0 [tag](https://github.com/alankarmisra/SwiftSiriWaveformView/releases/tag/2.0.0).

**Comment by rlxone** [comment]
Yeah, the same

**Comment by alankarmisra** [comment]
Sorry, I don't know how this totally escaped my radar. Will fix this soon!

**Comment by alankarmisra** [comment]
Updated the Pod to 2.1.0. You should get the most recent update now. Sorry for the insane delay. Totally slipped my radar. Reopen if something is still amiss.
