### ISSUE TITLE
Support for version older than ios 9.1?

### ISSUE THREAD

**Issue by gianu** [alankarmisra/SwiftSiriWaveformView#4]
First of all, thanks for this amazing project.

I'm trying to use SwiftSiriWaveformView on a personal project with a deployment target of 9.0 (and possibly older...not sure yet) and I'm getting an error

`Module file's  minimum deployment target is ios9.1 v9.1` on the following line

`import SwiftSiriWaveformView`

I'm using version 0.0.3 (according to Podfile.lock)

**Comment by gianu** [comment]
My Bad, I just found how to do this.

I change the deployment target in the pod folder.

Sorry!

**Comment by alankarmisra** [comment]
Perfect! Glad you found a fix. If you need any other help, do let me know.

Best,
