### ISSUE TITLE
Support for programmatically adding the SwiftSiriWaveformView

### ISSUE THREAD

**Issue by leonardocardoso** [alankarmisra/SwiftSiriWaveformView#7]
Not everyone uses exclusively Storyboards, it'd be nice if there was a support to instantiate simply like this:

``` swift
let bounds = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 60)
let siriWaveFormView: SwiftSiriWaveformView = SwiftSiriWaveformView(frame: bounds)
```

It seems you haven't created the default `init()`.

**Comment by kyramckenna** [comment]
I see that even if the noise changes in the background the wave never changes
